### ISSUE TITLE
add this Menu at Open Shell as 2nd option in Win10 and 11

### ISSUE THREAD

**Issue by blackcrack** [ronaldhoek/StartMenu2#1]
add this Startmenu2 at Open Shell as 2nd option in Win10, 11 and the more "older Systems",
could be cool , a normal Startmenu in the Systray, or make it possible to put OpenShell in the Systray as more better Startmenu in Win 11 .. \*vbg*

best  
Blacky

**Comment by ronaldhoek** [comment]
Sorry, don't understand what your wish is exactly...
